version: '3.9'

services:
  database:
    image: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "booker"
    ports:
      - "5432:5432"